// Copyright 2026 Cloud-Dog, Viewdeck Engineering Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @cloud-dog/tokens — Standalone CSS file output (no Tailwind required).

import { darkColors, lightColors } from "./colors";
import { fontFamily } from "./typography";
import { radii } from "./radii";
import { shadows } from "./shadows";
import { spacing } from "./spacing";

function emitBlock(selector: string, vars: Record<string, string>): string {
  const lines = Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

function normaliseKey(key: string): string {
  return key.replace(/\./g, "-");
}

function withColourAliases(vars: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = { ...vars };
  for (const key of Object.keys(vars)) {
    out[`color-${key}`] = `var(--${key})`;
  }
  return out;
}

export type GenerateCSSFileOptions = Readonly<{
  includeAliases?: boolean;
}>;

export function generateCSSFile(options: GenerateCSSFileOptions = {}): string {
  const includeAliases = options.includeAliases ?? true;

  const base: Record<string, string> = {
    ...Object.fromEntries(Object.entries(spacing).map(([k, v]) => [`space-${normaliseKey(k)}`, v])),
    ...Object.fromEntries(Object.entries(radii).map(([k, v]) => [`radius-${k}`, v])),
    ...Object.fromEntries(Object.entries(shadows).map(([k, v]) => [`shadow-${k}`, v])),
    "font-sans": fontFamily.sans.join(", "),
    "font-mono": fontFamily.mono.join(", "),
  };

  const light = { ...base, ...lightColors };
  const dark = { ...base, ...darkColors };

  const rootVars = includeAliases ? withColourAliases(light) : light;
  const darkVars = includeAliases ? withColourAliases(dark) : dark;

  return [
    "/* Generated by @cloud-dog/tokens. */",
    emitBlock(":root", rootVars),
    emitBlock(".dark", darkVars),
    "",
  ].join("\n\n");
}
